version: '3.2'

services:

  web:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /Users/jonathanolson/Projects/synapse_coding_challenge/
        target: /app
    command: /bin/sh -c "flask run"

  mongo:
    image: mongo:4.1.13
    container_name: mongodb
    volumes:
      - type: volume
        source: mongodbdata
        target: /data/db

volumes:
  mongodbdata:
    external: true